[tox]
envlist = py12, pep8, jshint
minversion = 3.1.0
skipsdist = True
ignore_basepython_conflict = True

[testenv]
setenv = VIRTUAL_ENV={envdir}
         PYTHONWARNINGS=default::DeprecationWarning
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
    -e .
commands =
     django-admin collectstatic --noinput --settings=langstroth.settings_test
     django-admin test --settings=langstroth.settings_test --exclude-tag selenium {posargs}

[testenv:pep8]
description = Run style checks.
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[flake8]
show-source = True
exclude = langstroth/migrations
select = H,O
# H404 Docstrings don't always start with a newline
# H405 Multiline docstrings are okay
ignore = H301,H403,H404,H405
import-order-style = pep8
application-import-names = langstroth

[testenv:cover]
setenv =
    {[testenv]setenv}
commands =
    coverage erase
    django-admin collectstatic --noinput --settings=langstroth.settings_test
    coverage run --source langstroth --parallel-mode -m django test --settings=langstroth.settings_test --exclude-tag selenium {posargs}
    coverage combine
    # Generate a new HTML report with the combined results
    # otherwise the HTML report will only show partial results
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report --fail-under=60 --skip-covered


[testenv:jshint]
allowlist_externals = {toxinidir}/.tox/jshint/node_modules/jshint/bin/jshint
deps =
    nodeenv
    pbr
commands = nodeenv -p
           npm install --prefix {envdir} jshint
           {envdir}/node_modules/jshint/bin/jshint .

[testenv:jscs]
deps =
    nodeenv
    pbr
commands = nodeenv -p
           npm install --prefix {envdir} jscs
           {envdir}/node_modules/jscs/bin/jscs --reporter inline .

[testenv:selenium]
passenv = DISPLAY
          TMPDIR
          GH_TOKEN
commands = django-admin test --settings=langstroth.settings_selenium --tag selenium {posargs}
