# Generated by Django 5.2.14 on 2026-07-27 04:31
#
# The `category` default backfills every existing row as an outage at
# ADD COLUMN time, so no data migration is needed. No index on
# `category`: the table is small (hundreds of rows) and every query
# also filters on other columns.
#
# `severity` becomes nullable: null is the marker for news, which has
# no severity. Model.clean() enforces that exactly the news rows are
# null.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(
                choices=[
                    ('outage', 'Outage'),
                    ('news', 'News'),
                    ('notice', 'Notice'),
                ],
                default='outage',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='severity',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'Minimal'), (2, 'Significant'), (3, 'Severe')],
                null=True,
            ),
        ),
    ]
