#!/bin/sh
# vim: set ts=2 et:

set -e

# Transition config to apache 2.4 compatable location.
dpkg-maintscript-helper mv_conffile \
  /etc/apache2/conf.d/langstroth.conf \
  /etc/apache2/conf-available/langstroth.conf \
  5.0-1 -- "$@"

#DEBHELPER#
