# Generated by Django 2.2.12 on 2021-07-02 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('IN', 'Investigating'), ('ID', 'Identified'), ('W', 'Watching'), ('F', 'Fixed')], max_length=2)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('severity', models.IntegerField(choices=[(1, 'Negligible'), (2, 'Minimal'), (3, 'Significant'), (4, 'Serious'), (5, 'Severe')])),
            ],
        ),
        migrations.CreateModel(
            name='OutageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('outage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outages.Outage')),
            ],
        ),
    ]
