# Generated by Django 4.2.3 on 2023-07-28 07:32

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='outage_managers')

    # It would be nice if we could also populate the permissions for
    # the group, but the perms will depend on the actual classes in the
    # at the time of the migration.  And also on the *current* policy.


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get(name='outage_managers').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
