# Generated by Django 4.2.8 on 2024-02-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0002_make_outage_manager_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outageupdate',
            options={'ordering': ['time', 'pk']},
        ),
        migrations.AlterField(
            model_name='outage',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outageupdate',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
