# Generated by Django 5.2.14 on 2026-05-24 23:30

from django.db import migrations


def delete_soft_deleted(apps, schema_editor):
    Outage = apps.get_model('outages', 'Outage')
    OutageUpdate = apps.get_model('outages', 'OutageUpdate')
    Outage.objects.filter(deleted=True).delete()
    OutageUpdate.objects.filter(deleted=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('outages', '0003_outage_modified_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outage',
            options={'ordering': ['-modification_time']},
        ),
        migrations.RunPython(
            delete_soft_deleted, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='outage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='outageupdate',
            name='deleted',
        ),
    ]
